// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFNVRkdhw9uT6D93IMn6WVClfovLV2Y3E',
    appId: '1:806292940238:web:a632cf5e207ea055cbf79f',
    messagingSenderId: '806292940238',
    projectId: 'learnfirebase-ab274',
    authDomain: 'learnfirebase-ab274.firebaseapp.com',
    storageBucket: 'learnfirebase-ab274.appspot.com',
    measurementId: 'G-EQ6V2CVY1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtHBSb91rHE3g0eSqzua-yrCpgN7FW-Bw',
    appId: '1:806292940238:android:f7829524518755f2cbf79f',
    messagingSenderId: '806292940238',
    projectId: 'learnfirebase-ab274',
    storageBucket: 'learnfirebase-ab274.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu9O-Lo19_OcMYz1QCqYUitkjeO_kb4ZA',
    appId: '1:806292940238:ios:bffed63c7a70f8d2cbf79f',
    messagingSenderId: '806292940238',
    projectId: 'learnfirebase-ab274',
    storageBucket: 'learnfirebase-ab274.appspot.com',
    iosClientId: '806292940238-dutguje5uukjhbqp7eecf91f1apkqdo0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu9O-Lo19_OcMYz1QCqYUitkjeO_kb4ZA',
    appId: '1:806292940238:ios:d8a0048fde4a4451cbf79f',
    messagingSenderId: '806292940238',
    projectId: 'learnfirebase-ab274',
    storageBucket: 'learnfirebase-ab274.appspot.com',
    iosClientId: '806292940238-sp60cck1mlut17g7tob525e8dplfv3mn.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat3.RunnerTests',
  );
}
